# system of equations as matrices

In [3]:
import numpy as np

In [5]:
A = np.matrix([[2, 3], [2, 4]])

print(A)

[[2 3]
 [2 4]]


In [6]:
# find determinant

print(np.linalg.det(A))

2.0


In [7]:
# check matrix is singular or not

if np.linalg.det(A) == 0:
    print("Matrix is singular")
else:
    print("Matrix is not singular")

Matrix is not singular


In [8]:
# 3x3 matrix

B = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(np.linalg.det(B))

if np.linalg.det(B) == 0:
    print("Matrix is singular")
else:
    print("Matrix is not singular")

0.0
Matrix is singular


In [11]:
# matrix transpose

print(A.T)

[[2 2]
 [3 4]]


In [12]:
# system of equations as matrices

A = np.matrix([[2, 3], [2, 4]])
B = np.matrix([[8], [10]])

# find inverse of matrix A

A_inv = np.linalg.inv(A)
print(A_inv)

[[ 2.  -1.5]
 [-1.   1. ]]


In [ ]:
# gaussian elimination method



# using numpy function



# using numpy function


A = np.matrix([[2, 3], [2, 4]])

B = np.matrix([[8], [10]])

X = np.linalg.solve(A, B)

print(X)

# using gaussian elimination method

def gauss_elimination(A, B):
    

[[1.]
 [2.]]
