In [2]:
import numpy as np

## creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## list vs numpy array

In [3]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.10879349708557129

 Numpy operation time:  0.008936882019042969


## creating array from scratch

In [4]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.37768156 0.49541728 0.88465756]
 [0.4331351  0.95522598 0.09723408]]
sequnce array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [5]:
vector = np.array([1, 2, 3, 4, 5])
print("vector: ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("matrix: \n", matrix)

tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("tensor: \n", tensor)

vector:  [1 2 3 4 5]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### array properties

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print("shape: ", arr.shape)
print("dimension: ", arr.ndim)
print("data type: ", arr.dtype)
print("size: ", arr.size)
print("item size: ", arr.itemsize)  
print("nbytes: ", arr.nbytes)


shape:  (5,)
dimension:  1
data type:  int64
size:  5
item size:  8
nbytes:  40


### array reshaping


In [14]:
original = np.arange(12)
print("original: \n", original)

flattened = original.flatten()
print("flattened: ", flattened)

reshaped = original.reshape(3, 4)
print("reshaped: \n", reshaped)

transposed = original.T
print("transposed: \n", transposed)




original: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
flattened:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transposed: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
