## Numpy array operations

In [19]:
import numpy as np


In [20]:
arr = np.array([1, 2, 3, 4, 5])
print("basic slicing", arr[1:4])
print("with step", arr[1:4:2])
print("negative index", arr[-3:-1])

basic slicing [2 3 4]
with step [2 4]
negative index [3 4]


In [21]:
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("2d array slicing", arr_2d[0, 1:4])
print("entire row", arr_2d[0, :])
print("entire column", arr_2d[:, 1])

2d array slicing [2 3 4]
entire row [1 2 3 4 5]
entire column [2 7]


### Sorting

In [22]:
unsorted_arr = np.array([3, 2, 0, 1])
print("sorting", np.sort(unsorted_arr))

arr_2d = np.array([[1, 2, 10, 4, 5], [6, 7, 8, 9, 10]])
print("sorting 2d array", np.sort(arr_2d, axis=0))



sorting [0 1 2 3]
sorting 2d array [[ 1  2  8  4  5]
 [ 6  7 10  9 10]]


## Filter

In [23]:
numbers = np.array([1, 2, 3, 4, 5])
even_numbers = numbers % 2 == 0
print("filtering", numbers[even_numbers])
print("filtering", numbers[numbers > 3])

filtering [2 4]
filtering [4 5]


## Filter with mask

In [25]:
mask = numbers > 3
print("masking", numbers[mask])

masking [4 5]


## Fancy indexing vs np.where()

In [30]:
indices = np.array([1, 3, 4])
print("using indices", numbers[indices])

where = np.where(numbers > 3, numbers*4, numbers)
print("where", where)

using indices [2 4 5]
where [ 1  2  3 16 20]


### adding and removing data

In [33]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("concatenation", np.concatenate((arr1, arr2)))
print("stacking", np.stack((arr1, arr2), axis=0))
print("stacking", np.stack((arr1, arr2), axis=1))


concatenation [1 2 3 4 5 6]
stacking [[1 2 3]
 [4 5 6]]
stacking [[1 4]
 [2 5]
 [3 6]]


## array compatibility

In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Comparison", np.equal(a, b))
print("Comparison", np.equal(a, a))

print("compatibility shape", a.shape == b.shape)

Comparison [False False False]
Comparison [ True  True  True]
compatibility shape True


In [40]:
orignal = np.array([[1,2], [3,4]])
new = np.array([5,6])

with_new_row = np.vstack((orignal, new))
print(orignal)
print(with_new_row)

new = np.array([[5], [6]])
with_new_column = np.hstack((orignal, new))
print(orignal)
print(with_new_column)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[1 2 5]
 [3 4 6]]


In [41]:
arr = np.array([1, 2, 3, 4, 5])
print("delete", np.delete(arr, 1))


delete [1 3 4 5]
